version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - OPENAI_API_KEY=NLv1Ij5my6gJhJ23jI9UT3BlbkFJXRQVXwAA6jKO45GNFIFA
    ports:
      - "3000:3000"

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - backend
